### ISSUE TITLE
Dangling session refresh is a problem in tests

### ISSUE THREAD

**Issue by praxxis** [keratin/authn-js#19]
After logging in, `updateStore` is called, which causes a [session refresh to be scheduled](https://github.com/keratin/authn-js/blob/34f3e9e5fabb33e3c8d0003664a383dc82a477b9/src/SessionManager.ts#L83). This causes problems in tests as there's no way to pause the test until the promise is resolved, clear the timeout, or just not cause the timeout to happen. It causes intermittent failures if the promise resolves before the end of a test run, as a server needs to exist to handle the refresh GET.

**Comment by cainlevy** [comment]
I'm uncertain how to resolve this at the moment.

The best workaround I can imagine would be to ensure that any stubbed JWTs created during a test have an expiration that is at least twice as long as the suite's longest possible duration. For example, if a suite takes 5 minutes to run, then any JWTs created during it should be valid for at least 10 minutes. This means the timeout would have a 5 minute delay, and should not accidentally trigger during the tests.

**Comment by praxxis** [comment]
oh which reminds me - at the moment we're mocking a JWT with _no_ expiration, which causes `NaN` to be computed in [`maintain`](https://github.com/keratin/authn-js/blob/34f3e9e5fabb33e3c8d0003664a383dc82a477b9/src/SessionManager.ts#L56). not sure if that should be an error. if it is, it might make figuring out that you need a long expiration easier?

**Comment by cainlevy** [comment]
👍
